version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pin_a_tree
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pin_a_tree
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
